import React from "react";
import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

export interface MorningReportPDFProps {
  date: string;
  orgName: string;
  stats: {
    tasks: number;
    emails: number;
    leads: number;
    hoursSaved: number | string;
  };
  highlights: string[];
  agentLog: Array<{
    time: string;
    action: string;
    result: string;
  }>;
}

export interface LeadReportPDFProps {
  date: string;
  searchCriteria: string;
  leads: Array<{
    name: string;
    company: string;
    title: string;
    email?: string | null;
    linkedin?: string | null;
    notes: string;
  }>;
}

const styles = StyleSheet.create({
  page: {
    backgroundColor: "#ffffff",
    color: "#111111",
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 36,
    paddingBottom: 44,
    paddingHorizontal: 36,
  },
  header: {
    alignItems: "center",
    borderBottom: "1 solid #d4d4d4",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 14,
  },
  brand: {
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: 1.2,
  },
  date: {
    color: "#525252",
    fontSize: 10,
  },
  subtitleBlock: {
    marginTop: 16,
    marginBottom: 16,
  },
  title: {
    fontSize: 19,
    fontWeight: 700,
    marginBottom: 4,
  },
  subtitle: {
    color: "#525252",
    fontSize: 11,
    lineHeight: 1.5,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  statCard: {
    border: "1 solid #d4d4d4",
    borderRadius: 10,
    flexGrow: 1,
    padding: 12,
  },
  statLabel: {
    color: "#525252",
    fontSize: 9,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  statValue: {
    fontSize: 18,
    fontWeight: 700,
  },
  section: {
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 10,
  },
  bulletRow: {
    flexDirection: "row",
    marginBottom: 6,
    paddingRight: 8,
  },
  bullet: {
    width: 10,
  },
  bulletText: {
    color: "#262626",
    flex: 1,
    lineHeight: 1.5,
  },
  table: {
    border: "1 solid #d4d4d4",
    borderRadius: 10,
    overflow: "hidden",
  },
  tableHeader: {
    backgroundColor: "#111111",
    color: "#ffffff",
    flexDirection: "row",
    fontSize: 9,
    fontWeight: 700,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  tableRow: {
    borderBottom: "1 solid #e5e5e5",
    flexDirection: "row",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  tableRowLast: {
    borderBottom: "0 solid transparent",
  },
  tableCell: {
    fontSize: 9,
    lineHeight: 1.45,
    paddingRight: 8,
  },
  summary: {
    borderTop: "1 solid #d4d4d4",
    color: "#404040",
    fontSize: 10,
    marginTop: 16,
    paddingTop: 12,
  },
  footer: {
    borderTop: "1 solid #d4d4d4",
    bottom: 20,
    color: "#737373",
    fontSize: 9,
    left: 36,
    paddingTop: 10,
    position: "absolute",
    right: 36,
    textAlign: "center",
  },
});

function ReportFooter() {
  return (
    <Text fixed style={styles.footer}>
      Generated by Inceptive AI · app.inceptive-ai.com
    </Text>
  );
}

export function MorningReportPDF({ date, orgName, stats, highlights, agentLog }: MorningReportPDFProps) {
  return (
    <Document title={`Inceptive Morning Report - ${orgName}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>INCEPTIVE</Text>
          <Text style={styles.date}>{date}</Text>
        </View>

        <View style={styles.subtitleBlock}>
          <Text style={styles.title}>Morning Agent Report</Text>
          <Text style={styles.subtitle}>{orgName}</Text>
        </View>

        <View style={styles.statsRow}>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Tasks</Text>
            <Text style={styles.statValue}>{stats.tasks}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Emails</Text>
            <Text style={styles.statValue}>{stats.emails}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Leads</Text>
            <Text style={styles.statValue}>{stats.leads}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Hours Saved</Text>
            <Text style={styles.statValue}>{stats.hoursSaved}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Tonight&apos;s Highlights</Text>
          {highlights.length > 0 ? (
            highlights.map((highlight, index) => (
              <View key={`${highlight}-${index}`} style={styles.bulletRow}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.bulletText}>{highlight}</Text>
              </View>
            ))
          ) : (
            <Text style={styles.bulletText}>No highlights were recorded for this reporting period.</Text>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Full Activity Log</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableCell, { width: "18%" }]}>Time</Text>
              <Text style={[styles.tableCell, { width: "28%" }]}>Action</Text>
              <Text style={[styles.tableCell, { width: "54%", paddingRight: 0 }]}>Result</Text>
            </View>
            {agentLog.map((entry, index) => (
              <View
                key={`${entry.time}-${entry.action}-${index}`}
                style={[styles.tableRow, index === agentLog.length - 1 ? styles.tableRowLast : {}]}
              >
                <Text style={[styles.tableCell, { width: "18%" }]}>{entry.time}</Text>
                <Text style={[styles.tableCell, { width: "28%" }]}>{entry.action}</Text>
                <Text style={[styles.tableCell, { width: "54%", paddingRight: 0 }]}>{entry.result}</Text>
              </View>
            ))}
          </View>
        </View>

        <ReportFooter />
      </Page>
    </Document>
  );
}

export function LeadReportPDF({ date, searchCriteria, leads }: LeadReportPDFProps) {
  return (
    <Document title={`Inceptive Lead Research Report - ${date}`}>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Lead Research Report</Text>
          <Text style={styles.date}>{date}</Text>
        </View>

        <View style={styles.subtitleBlock}>
          <Text style={styles.subtitle}>Search Criteria</Text>
          <Text style={styles.title}>{searchCriteria}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableCell, { width: "14%" }]}>Name</Text>
            <Text style={[styles.tableCell, { width: "14%" }]}>Company</Text>
            <Text style={[styles.tableCell, { width: "14%" }]}>Title</Text>
            <Text style={[styles.tableCell, { width: "18%" }]}>Email</Text>
            <Text style={[styles.tableCell, { width: "18%" }]}>LinkedIn</Text>
            <Text style={[styles.tableCell, { width: "22%", paddingRight: 0 }]}>Notes</Text>
          </View>
          {leads.map((lead, index) => (
            <View
              key={`${lead.name}-${lead.company}-${index}`}
              style={[styles.tableRow, index === leads.length - 1 ? styles.tableRowLast : {}]}
            >
              <Text style={[styles.tableCell, { width: "14%" }]}>{lead.name}</Text>
              <Text style={[styles.tableCell, { width: "14%" }]}>{lead.company}</Text>
              <Text style={[styles.tableCell, { width: "14%" }]}>{lead.title}</Text>
              <Text style={[styles.tableCell, { width: "18%" }]}>{lead.email || "-"}</Text>
              <Text style={[styles.tableCell, { width: "18%" }]}>{lead.linkedin || "-"}</Text>
              <Text style={[styles.tableCell, { width: "22%", paddingRight: 0 }]}>{lead.notes}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.summary}>{`${leads.length} leads found matching criteria`}</Text>

        <ReportFooter />
      </Page>
    </Document>
  );
}
