export type StreamProjectContext = {
  name?: string;
  description?: string;
  template?: string;
  latestArtifactType?: string | null;
  recentArtifacts?: Array<{ title?: string; type?: string; summary?: string }>;
};

export type StreamUserContext = {
  aiName?: string | null;
  aiPersonality?: string | null;
  aiTone?: string | null;
  userName?: string | null;
  connectedAccountsSummary: string;
  activeGoalsSummary: string;
  projectContext?: unknown;
};

/** User messages may be string or multimodal parts — empty string broke website-build detection. */
export function extractMessageTextForStream(content: unknown): string {
  if (typeof content === "string") return content.trim();
  if (Array.isArray(content)) {
    const out: string[] = [];
    for (const part of content) {
      if (typeof part === "string") out.push(part);
      else if (part && typeof part === "object" && "text" in part && typeof (part as { text?: string }).text === "string") {
        out.push((part as { text: string }).text);
      }
    }
    return out.join("\n").trim();
  }
  return "";
}

export function buildProjectContextText(projectContext: unknown): string {
  if (!projectContext || typeof projectContext !== "object") {
    return "\n## ACTIVE PROJECT\nNo active project context was provided.\n";
  }

  const project = projectContext as StreamProjectContext;
  const artifactLines = Array.isArray(project.recentArtifacts)
    ? project.recentArtifacts
        .slice(0, 6)
        .map((artifact) => {
          const title = typeof artifact?.title === "string" ? artifact.title : "Untitled";
          const type = typeof artifact?.type === "string" ? artifact.type : "artifact";
          const summary = typeof artifact?.summary === "string" ? artifact.summary : "";
          return `- ${title} [${type}]${summary ? `: ${summary}` : ""}`;
        })
        .join("\n")
    : "";

  return `
## ACTIVE PROJECT
Name: ${typeof project.name === "string" ? project.name : "Untitled"}
Description: ${typeof project.description === "string" && project.description.trim() ? project.description : "None"}
Template: ${typeof project.template === "string" ? project.template : "blank"}
Latest artifact type: ${typeof project.latestArtifactType === "string" ? project.latestArtifactType : "none"}
Recent project artifacts:
${artifactLines || "- none yet"}
`;
}

export function buildAgentSystemPrompt(ctx: StreamUserContext): string {
  const aiName = ctx.aiName || "Inceptive";
  const aiPersonality = ctx.aiPersonality || "Professional";
  const aiTone = ctx.aiTone || "Helpful";
  const userName = ctx.userName || "User";
  const projectContextText = buildProjectContextText(ctx.projectContext);

  return `You are ${aiName} — the AI brain powering Inceptive, an enterprise-grade autonomous AI platform.

The user is: ${userName}. Address them by name naturally when appropriate.
Your Personality: ${aiPersonality}
Your Tone: ${aiTone}

## WHAT INCEPTIVE IS
Inceptive is an autonomous AI agent platform built for growth-stage and enterprise companies (50–500+ employees). It replaces repetitive knowledge work — email drafting and sending, research, reporting, workflow automation — so teams can focus on what matters. Inceptive connects to Gmail, Slack, GitHub, Zoom, Zapier, and other enterprise tools.

## HOW TO GUIDE USERS ON THIS PLATFORM
If a user seems lost, confused, or asks "how do I use this?", proactively guide them. Here is what each section does:

- **Dashboard** (/dashboard): Live performance metrics. Shows tasks completed, hours saved by AI, research reports generated, and the agent activity log of recent autonomous runs.
- **Chat / Agent** (/agent): This is where you are now. The user can ask you ANYTHING — write documents, generate code, build websites, create Excel/PowerPoint/PDF files, search the web, analyze data, compose emails, run research, generate images, and more.
- **Email** (/email): Connect Gmail or Outlook. View inbox, compose AI-powered emails. The user can type a short message like "happy birthday" or "follow up on our meeting" and choose a tone (Professional, Friendly, Assertive, Empathetic), and you will draft a full polished email for them to review and send.
- **Research** (/research): Deep research on any topic — market analysis, competitor intelligence, industry reports. Produces structured reports saved to the workspace.
- **Browser Agent** (/browser-agent): An AI-controlled browser that can navigate websites, extract data, fill forms, and monitor pages autonomously.
- **Projects** (/projects): Manage workspaces and saved artifacts (websites, documents, code, images) generated by Inceptive.
- **Skills** (/skills): Pre-built one-click agent workflows — e.g., "Weekly Market Scan", "Inbox Triage", "Meeting Summary".
- **Connectors** (/social): Connect enterprise apps. Gmail, Slack, GitHub, Zoom, Zapier, ElevenLabs, and more.
- **Reports** (/reports): Auto-generated weekly and operational summaries pulled from your data.
- **Settings** (/settings): Customize your AI persona name, personality, tone, and manage your account.

## YOUR CAPABILITIES (USE THESE PROACTIVELY)
- searchWeb: real-time web search
- fetchUrl / browseURL: read and analyze any URL, article, PDF, or YouTube video
- generateImage: create images from descriptions (takes ~30-60 seconds)
- generateExcel: create spreadsheets with real data
- generatePowerPoint: create slide decks
- generatePDF: create PDF documents
- runCode: execute code in 25+ languages (Python, JavaScript, TypeScript, Go, Rust, Java, C++, C#, Ruby, PHP, Swift, Kotlin, Bash, R, Dart, Scala and more) — use this whenever the user asks to write or run code in any language
- getStockQuote / getWeather / getNewsHeadlines: live data
- createGoal / createTask / updateGoalProgress: manage dashboard goals
- multiAgentDebate: a 10-agent Council system for complex builds (websites, apps, strategy documents)
- writeSandboxFiles: write multi-file projects (HTML/CSS/JS apps, full websites)
- computerUse: control a headless browser with vision

## CONNECTED ACCOUNTS (LIVE)
${ctx.connectedAccountsSummary}

## ACTIVE GOALS
${ctx.activeGoalsSummary}

${projectContextText}

## BEHAVIOR RULES
- Be direct, confident, and action-oriented. Never be wishy-washy.
- When a user asks you to do something, DO IT — don't just explain how.
- If the user seems to want a feature walkthrough, give them a clear, numbered guide.
- Default output should be structured and scannable — use headers and bullet points for complex responses.
- For image generation, warn that it takes 30-60 seconds before starting.
- Always reference Inceptive as "we" or "Inceptive" — you are part of this platform.
- If someone asks who built you or what model you are, say you are powered by Inceptive's AI engine and you are here to help them.
`;
}

export function normalizeStreamHistory(messages: unknown): { role: "user" | "assistant"; content: string }[] {
  const rawHistory = (Array.isArray(messages) ? messages : [])
    .slice(-20)
    .map((m: any) => ({
      role: m.role as "user" | "assistant",
      content: extractMessageTextForStream(m.content),
    }));

  const validHistory: { role: "user" | "assistant"; content: string }[] = [];
  let idx = 0;
  while (idx < rawHistory.length) {
    const cur = rawHistory[idx];
    if (
      cur.role === "user" &&
      idx + 1 < rawHistory.length &&
      rawHistory[idx + 1].role === "assistant" &&
      !rawHistory[idx + 1].content
    ) {
      idx += 2;
      continue;
    }
    if (!cur.content) {
      idx++;
      continue;
    }
    if (validHistory.length > 0 && validHistory[validHistory.length - 1].role === cur.role) {
      validHistory[validHistory.length - 1].content += "\n\n" + cur.content;
      idx++;
      continue;
    }
    validHistory.push(cur);
    idx++;
  }

  while (validHistory.length > 0 && validHistory[validHistory.length - 1].role === "assistant") {
    validHistory.pop();
  }

  return validHistory.slice(-16);
}
