import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { getAuthenticatedUserIdFromRequest } from "@/lib/api-auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  const userId = await getAuthenticatedUserIdFromRequest(req);
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await req.json();
    const {
      content = "",
      title = "Document",
      filename = "document.pdf",
      margins = { top: 50, bottom: 50, left: 50, right: 50 },
    } = body;

    if (!content || typeof content !== "string") {
      return NextResponse.json(
        { error: "Invalid content: expected non-empty string" },
        { status: 400 }
      );
    }

    // Create a Promise that resolves with the PDF buffer
    return new Promise((resolve) => {
      try {
        const doc = new PDFDocument({
          margin: margins.top,
          size: "A4",
        });

        const chunks: Buffer[] = [];
        
        doc.on("data", (chunk: Buffer) => chunks.push(chunk));
        doc.on("end", () => {
          const buffer = Buffer.concat(chunks);
          const base64 = buffer.toString("base64");

          resolve(
            NextResponse.json({
              success: true,
              filename,
              title,
              content: base64,
              mimeType: "application/pdf",
              pageCount: doc.bufferedPageRange().count,
            })
          );
        });

        // Add title
        doc.fontSize(24).fillColor("#2E4057").text(title, {
          align: "center",
        });
        
        doc.moveDown(2);

        // Add content
        doc.fontSize(12).fillColor("#333333");

        // Split content into paragraphs and add
        const paragraphs = content.split(/\n\n+/);
        for (const paragraph of paragraphs) {
          if (paragraph.trim()) {
            doc.text(paragraph.trim(), {
              align: "left",
              lineGap: 4,
            });
            doc.moveDown(0.5);
          }
        }

        // Add footer
        doc.moveDown(2);
        doc.fontSize(10).fillColor("#999999");
        doc.text("Generated by Inceptive AI", {
          align: "center",
        });

        doc.end();
      } catch (err: any) {
        resolve(
          NextResponse.json(
            { error: err.message || "Failed to generate PDF" },
            { status: 500 }
          )
        );
      }
    });
  } catch (error: any) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PDF" },
      { status: 500 }
    );
  }
}

// Simple GET endpoint
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const content = searchParams.get("content") || "Hello from Inceptive AI!";
  const title = searchParams.get("title") || "Document";
  const filename = searchParams.get("filename") || "document.pdf";

  return new Promise((resolve) => {
    try {
      const doc = new PDFDocument();
      const chunks: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => {
        const buffer = Buffer.concat(chunks);
        const base64 = buffer.toString("base64");

        resolve(
          NextResponse.json({
            success: true,
            filename,
            content: base64,
            mimeType: "application/pdf",
          })
        );
      });

      doc.fontSize(24).fillColor("#2E4057").text(title, { align: "center" });
      doc.moveDown(2);
      doc.fontSize(12).fillColor("#333333").text(content, { align: "left" });
      doc.moveDown(2);
      doc.fontSize(10).fillColor("#999999").text("Generated by Inceptive AI", { align: "center" });

      doc.end();
    } catch (err: any) {
      resolve(
        NextResponse.json({ error: err.message || "Failed to generate PDF" }, { status: 500 })
      );
    }
  });
}
