import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { getAuthenticatedUserIdFromRequest } from "@/lib/api-auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: Request): Promise<NextResponse> {
  const userId = await getAuthenticatedUserIdFromRequest(req);
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await req.json();
    const {
      content = "",
      title = "Document",
      filename = "document.pdf",
    } = body;

    if (!content || typeof content !== "string") {
      return NextResponse.json(
        { error: "Invalid content: expected non-empty string" },
        { status: 400 }
      );
    }

    // Generate PDF synchronously
    const chunks: Buffer[] = [];
    
    const doc = new PDFDocument({
      size: "A4",
    });

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    
    // Wait for PDF to be generated
    await new Promise<void>((resolve, reject) => {
      doc.on("end", resolve);
      doc.on("error", reject);
      
      // Add title
      doc.fontSize(24).fillColor("#2E4057").text(title, {
        align: "center",
      });
      
      doc.moveDown(2);

      // Add content
      doc.fontSize(12).fillColor("#333333");
      const paragraphs = content.split(/\n\n+/);
      for (const paragraph of paragraphs) {
        if (paragraph.trim()) {
          doc.text(paragraph.trim(), {
            align: "left",
            lineGap: 4,
          });
          doc.moveDown(0.5);
        }
      }

      // Add footer
      doc.moveDown(2);
      doc.fontSize(10).fillColor("#999999");
      doc.text("Generated by Inceptive AI", {
        align: "center",
      });

      doc.end();
    });

    const buffer = Buffer.concat(chunks);
    const base64 = buffer.toString("base64");

    return NextResponse.json({
      success: true,
      filename,
      title,
      content: base64,
      mimeType: "application/pdf",
    });
  } catch (error: any) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PDF" },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    message: "Use POST method to generate PDF",
    example: {
      content: "Your text content here",
      title: "My Document",
      filename: "document.pdf"
    }
  });
}
